<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="CatagoryMaster.aspx.cs" Inherits="TaskWebsite.CatagoryMaster" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
   
    <style>


         
    table {
        border: 2px solid black; 
        margin: 0 auto;
        width: 600px;
        font-size: 1.8em; 
        font-family: Arial, sans-serif; 
         margin-top: 50px;
        
    }

    .h2 {
        font-size: 4em;
    }

    .align-middle {
        vertical-align: middle; 
    }

    .text-center {
        text-align: center; 
    }
    .table tbody tr:hover {
        background-color: cadetblue;
    }
    /* Change the header color */
#CategoryGridView th {
    background-color: #007bff;
    color: #fff;
}

/* Change the row hover color */
#CategoryGridView tbody tr:hover {
    background-color: #f5f5f5;
}

/* Center the contents of the cells */
#CategoryGridView td, #CategoryGridView th {
    text-align: center;
}

/* Change the edit and delete buttons */
#CategoryGridView .btn-default {
    background-color: #f0ad4e;
    border-color: #eea236;
    color: #fff;
}

/* Style the search button */
#SearchButton {
    background-color: #007bff;
    border-color: #007bff;
    color: #fff;
}

  .gridview-style {
        border: 1px solid #ddd;
        border-collapse: collapse;
    }
    .gridview-style th, .gridview-style td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    .gridview-style th {
        background-color: #f2f2f2;
    }
    .gridview-style tr:nth-child(even) {
        background-color: #f2f2f2;
    }      
  

</style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container13">
        <table cellpadding="4" cellspacing="4" class="table">
            <tr>
                <td colspan="2" class="text-center h2">CATEGORY MASTER</td>
            </tr>
           
            <tr>
                <td class="align-middle">Category Name</td>
                <td>
                    <asp:TextBox ID="CatagoryNameTextBox" runat="server" CssClass="form-control"></asp:TextBox>
                    <asp:RequiredFieldValidator runat="server" ErrorMessage="Please Enter Category Name" ControlToValidate="CatagoryNameTextBox" ForeColor="Red"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="align-middle">Description</td>
                <td>
                    <asp:TextBox ID="DescriptionTextBox" runat="server" CssClass="form-control"></asp:TextBox>
                    <asp:RequiredFieldValidator runat="server" ErrorMessage="Please Enter Discription" ControlToValidate="DescriptionTextBox" ForeColor="Red"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <asp:Button ID="SubmitButton" runat="server" OnClick="SubmitButton_Click" Text="Submit" CssClass="btn btn-primary" />
                    
                    
                </td>
            </tr>
        </table>
       <asp:TextBox ID="SearchTextBox" runat="server" CssClass="form-control"></asp:TextBox>
<asp:Button ID="SearchButton" runat="server" Text="Search" CssClass="btn btn-primary" Onclick="SearchButton_Click1" CausesValidation="false"/>

        <asp:GridView  id="CategoryGridView"  CssClass=" gridview-style table table-striped table-bordered" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="CategoryGridView_SelectedIndexChanged" DataKeyNames="ID">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="CategoryName" HeaderText="CategoryName" SortExpression="CategoryName" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            </Columns>
       
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:NewTaskConnectionString %>" DeleteCommand="DELETE FROM [CategoryMaster] WHERE [ID] = @ID" InsertCommand="INSERT INTO [CategoryMaster] ([CategoryName], [Description]) VALUES (@CategoryName, @Description)" SelectCommand="SELECT [ID], [CategoryName], [Description] FROM [CategoryMaster]" UpdateCommand="UPDATE [CategoryMaster] SET [CategoryName] = @CategoryName, [Description] = @Description WHERE [ID] = @ID">
            <DeleteParameters>
                <asp:Parameter Name="ID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="CategoryName" Type="String" />
                <asp:Parameter Name="Description" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="CategoryName" Type="String" />
                <asp:Parameter Name="Description" Type="String" />
                <asp:Parameter Name="ID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

    </div>
</asp:Content>
